name: Validação Extendida do Oráculo

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  oraculo-check:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v5

      - name: Apagar build antigo
        run: rm -rf dist tsconfig.tsbuildinfo

      - name: Instalar Node.js
<<<<<<< HEAD
        uses: actions/setup-node@v4
=======
        uses: actions/setup-node@v5
>>>>>>> 143fdc685b941d444a171bd725a9366d38196e85
        with:
          node-version: '24.x'

      - name: Instalar dependências
        run: npm ci

      - name: Checagens de estilo (lint + types + prettier)
        run: npm run check:style

      - name: Auditoria de dependências (permitindo nível moderado)
        run: npm run security:deps

      - name: Compilar projeto
        run: npm run build

      - name: Testar comandos principais do Oráculo
        run: |
          node dist/bin/index.js --help
          node dist/bin/index.js diagnosticar --help
          node dist/bin/index.js guardian --help
          node dist/bin/index.js podar --help
          node dist/bin/index.js reestruturar --help
          node dist/bin/index.js atualizar --help

      - name: Rodar testes e cobertura
        run: npm run coverage && npm run coverage:gate

      - name: Exportar artefato dist
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: oraculo-dist
          path: dist
