name: Validação do Oráculo

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  oraculo-check: 
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Instalar dependências
        run: npm ci

      - name: Instalar tipos necessários
        run: |
          npm install --save-dev \
            @types/node \
            @types/json-schema \
            @types/estree \
            @types/micromatch \
            @types/braces \
            @types/babel__traverse

      - name: Verificar tipos (typecheck)
        run: npx tsc --noEmit

      - name: Verificar lint (eslint)
        run: npx eslint . --ext .ts

      - name: Verificar formatação (prettier)
        run: npx prettier . --check