name: CI Principal

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Instalar dependências
        run: npm ci

      - name: Verificações de estilo (lint + prettier + types)
        run: npm run check:style

      - name: Audit rápido de dependências (não falha build)
        run: npm run security:deps

      - name: Cobertura completa
        run: npm run coverage

      - name: Gate de cobertura
        run: npm run coverage:gate

      - name: Build para testes E2E
        run: npm run build

      - name: Testes E2E (binário)
        run: npm run test:e2e

      - name: Gate de performance (comparação últimos snapshots)
        if: ${{ always() }}
        run: |
          if [ -d docs/perf ]; then
            npm run perf:compare || echo "Sem baseline suficiente para compare inicial";
            npm run perf:gate || echo "(Aviso) Regressão de performance detectada";
          else
            echo "Pasta docs/perf inexistente - pule perf gate";
          fi

      - name: Publicar dist como artifact
        uses: actions/upload-artifact@v4
        with:
          name: oraculo-dist
          path: dist
