name: license-gate

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]

jobs:
  license-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
<<<<<<< HEAD
      - uses: actions/setup-node@v4
=======
      - uses: actions/setup-node@v5
>>>>>>> 143fdc685b941d444a171bd725a9366d38196e85
        with:
          node-version: '24'
      - run: npm ci
      - name: Fail on copyleft licenses
        run: node scripts/auditar-licencas.mjs --fail-on-copyleft
