name: Monitorar dependências

on:
  schedule:
    - cron: '0 8 * * 1' # toda segunda-feira às 8h UTC
  workflow_dispatch:

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v5
      - name: Instalar Node.js
<<<<<<< HEAD
        uses: actions/setup-node@v4
=======
        uses: actions/setup-node@v5
>>>>>>> 143fdc685b941d444a171bd725a9366d38196e85
        with:
          node-version: 24.x
      - name: Instalar dependências
        run: npm ci
      - name: Verificar dependências desatualizadas
        run: npx npm-check-updates || true
